---
title: "Capstone: Lasso"
author: "Andrew Knittle"
date: "`r paste('Generated on', Sys.Date())`" 
output: 
  html_document: 
    # try readable or cosmo
    # default (default), try kable, tibble, or paged as an option
    # Options are none (default), show, and hide
    # default is null, try my_style_file.css
    toc: TRUE
    toc_depth: 3
    toc_float: FALSE
    highlight: haddock
    theme: flatly
    df_print: paged
    code_folding: none
    self_contained: TRUE
---

```{r setup, include=FALSE}
# --------------------------------------
# Clean and Prep Environment
rm(list=ls())
set.seed(123)

# --------------------------------------
# Load Libraries
library(pacman)
p_load(ggplot2)
p_load(ISLR)
p_load(dplyr)
p_load(psych)
p_load(ggpubr)
p_load(kableExtra)
p_load(corrplot)
p_load(tidyverse)
p_load(tidyr)
p_load(caret)
p_load(MASS)
p_load(glm.predict)
p_load(glmnet)
p_load(leaps)

# Formatting----------------------------
p_load(kable)
p_load(kableExtra)
p_load(DT)
p_load(reactable)

# --------------------------------------
# Read Data
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

logDustData = as.data.frame(read.csv('Data/logDustData_Reduced.csv',header=T,sep=','))
logDustData <- logDustData[-1]
logDustData <- logDustData[-1]
logDustData$CASESTAT <- as.factor(logDustData$CASESTAT)
logDustData <- na.omit(logDustData[,c(1:27, 30)])

# --------------------------------------
# Read helper script
source("Exploratory_Support_Scripts.R")
source("Script_Library.R")
source("CrossValidation_Library.R")
source("Model_Building_Library.R")


```


# In Review...

The following is a comparative Data Frame that shows all of the error rates in one large group.

```{r Review, echo=FALSE, fig.cap= "Review", out.height="100%", out.width="100%", warning=FALSE, comment=FALSE, warning=FALSE}

# TODO: Should probably make this part automated instead of hardcoded... but a little late for now...
rateNames <- c("Error Rate",	"False Positive Rate (Fall-Out)",	"False Negative Rate (Miss Rate)",	
               "True Positive Rate (Sensitivity)",	"True Negative Rate (Specificity)",	"Precision (PPV)",	
               "Negative Predictive Value (NPV)")
logisticResults <- c(0.4135593,	0.742126,	0.1651786,	0.8348214,	0.257874,	0.598081,	0.5413223)
lassoResults <- c(0.4279661,	0.8326772,	0.1220238,	0.8779762,	0.1673228,	0.5824284,	0.508982)
ldaResults <- c(0.4186441,	0.7047244,	0.202381,	0.797619,	0.2952756,	0.5995526,	0.5244755)
rfResults <- c(0.4483051,	0.7106299,	0.25,	0.75,	0.2893701,	0.582659,	0.4666667)

finalDF <- rbind.data.frame(logisticResults,lassoResults,ldaResults,rfResults)
colnames(finalDF) <- rateNames
rownames(finalDF) <- c("Logistic", "Lasso", "LDA", "Random Forest")

BuYlRd <- function(x) rgb(colorRamp(c("#7fb7d7", "#ffffbf", "#fc8d59"))(x), maxColorValue = 255)

alpha = 0.25
beta = 0.5

finalDF %>%
    kbl() %>%
    kable_paper("hover", full_width = F) %>%
    column_spec(2, color = "white", background = spec_color(finalDF[,1], begin = alpha, end= beta, direction=-1))%>%
    column_spec(3, color = "white", background = spec_color(finalDF[,2], begin = alpha, end= beta, direction=-1))%>%
    column_spec(4, color = "white", background = spec_color(finalDF[,3], begin = alpha, end= beta, direction=-1))%>%
    column_spec(5, color = "white", background = spec_color(finalDF[,4], begin = alpha, end= beta, direction=-1))%>%
    column_spec(6, color = "white", background = spec_color(finalDF[,5], begin = alpha, end= beta, direction=-1))%>%
    column_spec(7, color = "white", background = spec_color(finalDF[,6], begin = alpha, end= beta, direction=-1))%>%
    column_spec(8, color = "white", background = spec_color(finalDF[,7], begin = alpha, end= beta, direction=-1))

# datatable(finalDF)

reactable(
  finalDF,
  defaultColDef = colDef(
    style = function(value) {
      if (!is.numeric(value)) return()
      color <- BuYlRd(value)
      list(background = color)
    },
    format = colFormat(digits = 4),
    minWidth = 50
  ),
  columns = list(
    .rownames = colDef(name = "Year", sortable = TRUE, align = "left")
  ),
  bordered = TRUE
)

```



