---
title: "Capstone: Neural Network"
author: "Andrew Knittle"
date: "`r paste('Generated on', Sys.Date())`" 
output: 
  html_document: 
    # try readable or cosmo
    # default (default), try kable, tibble, or paged as an option
    # Options are none (default), show, and hide
    # default is null, try my_style_file.css
    toc: TRUE
    toc_depth: 3
    toc_float: FALSE
    highlight: haddock
    theme: flatly
    df_print: paged
    code_folding: none
    self_contained: TRUE
---

```{r setup, include=FALSE}
# --------------------------------------
# Clean and Prep Environment
rm(list=ls())
set.seed(123)

# --------------------------------------
# Load Libraries
library(pacman)
p_load(ggplot2)
p_load(dplyr)
p_load(psych)
p_load(ggpubr)
p_load(kableExtra)
p_load(corrplot)
p_load(tidyverse)
p_load(caret)
p_load(MASS)
p_load(ISLR)
p_load(glm.predict)
p_load(glmnet)
p_load(modelr)
p_load(boot)
p_load(pROC)
p_load(deepnet)
p_load(mlbench)

# --------------------------------------
# Read Data
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

dustData = as.data.frame(read.csv('Data/dustData_Reduced.csv',header=T,sep=',')) # OG dataset
dustData <- dustData[-1]
dustData$CASESTAT <- as.factor(dustData$CASESTAT)
dustData <- na.omit(dustData[,c(1:27, 30)])

logDustData = as.data.frame(read.csv('Data/logDustData_Reduced.csv',header=T,sep=','))
logDustData <- logDustData[-1]
logDustData <- logDustData[-1]
logDustData$CASESTAT <- as.factor(logDustData$CASESTAT)
logDustData <- na.omit(logDustData[,c(1:27, 30)])

train_DustData <- as.data.frame(read.csv('Data/Training Set_0.9_May 25 2021.csv',header=T,sep=','))[-1]
#train_DustData$CASESTAT <- as.numeric(train_DustData$CASESTAT)
train_DustData$CASESTAT <- as.factor(train_DustData$CASESTAT)
train_DustData <- na.omit(train_DustData[,c(1:27, 30)])

# --------------------------------------
# Read helper script
source("Exploratory_Support_Scripts.R")
source("CrossValidation_Library.R")
source("Script_Library.R")


```




```{r Model Building, echo=FALSE, fig.cap= "Model Building", out.height="100%", out.width="100%", warning=FALSE, comment=FALSE, warning=FALSE}

# Prep the data to work with the "deepnet" package
# https://srdas.github.io/DLBook/DeepLearningWithR.html

cancerVal = as.numeric(as.matrix(logDustData$CASESTAT)) # Cast the dependent variable as a matrix
predictMatrix = as.matrix(logDustData[,1:27], ncol=27) # Build Matrix of predictors

# Begin the training
# hidden is the number of nodes in the first layer is x
# nn <- nn.train(predictMatrix, cancerVal, hidden = c(5))
buildNetwork(cancerVal, predictMatrix, c(5))

```



